version: "3"

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./assets:/var/www/html/wp-content/themes/theme/assets
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
networks:
  default:
    external:
      name: dockerdevenvironment_default
  # vite:
  #   build:
  #     context: ./path/to/vite/project
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./path/to/vite/project:/usr/src/app
